services:
  - type: web
    name: team-maestro-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python seed_data.py
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
